### ISSUE TITLE
ubuntu12.04でのコンパイル

### ISSUE THREAD

**Issue by yukimori** [kazuki/jubatus-bench#3]
ubuntu12.04
g++ 4.6.3-1
の環境下では以下でコンパイルすることができました

 g++ classifier.cpp common.cpp  -o classifier -O2 -Wall -Wno-deprecated-declarations -L../jubatus_core/lib -I../jubatus_core/build -I../jubatus_core -ljubatus_core -ljubatus_util_concurrent -ljubatus_util_data -ljubatus_util_lang -ljubatus_util_math -ljubatus_util_system -ljubatus_util_text -lmsgpack -lrt

変更点1）classifier.cpp common.cpp -o classifier を前に
gcc 4.6.3ではコンパイル時に指定する順序が規定されているようで、変更前の状態だとエラーがでるので前方に移動させました

変更点2）-lrtの付与
undefined reference to `clock_gettime'
のエラーがでたので、librt.soを明示的に読むこむように-lrtを付与しました

**Comment by kazuki** [comment]
ありがとうございます．
9fcd77035d69bcd1860ad155f59d7e57e83e2a8b で修正しました
